feat: shadow colors
KyoriPowered/adventure pull request #1124
Opened 2024-11-01 06:48 UTC by kashike

2024-11-01 09:20 UTC, MiniDigger commented on api/src/main/java/net/kyori/adventure/text/format/ShadowColor.java
> +  static ShadowColor shadowColor(final int value) {
should document the format of that int
and maybe we can have overloads that take a textcolor + alpha?

2024-11-01 09:51 UTC, MiniDigger commented on api/src/main/java/net/kyori/adventure/text/format/ShadowColor.java
> +    style.color(this);
```suggestion
    style.shadowColor(this);
```

2024-11-01 11:48 UTC, kezz commented
We need a concept of "no shadow" that exists outside of creating a shadow colour with a magic number value. I'm also not sure I like the ShadowColor object existing as it does, I think I'd prefer it to be an interface implemented by either a singleton "none" object or a textcolor + alpha value. As we need some sort of ARGBLike interface (most platforms already have a colour + alpha object), I think we should try and ensure we don't duplicate API here.

Ideally I think the API would allow for all of the following:
```java
style.shadowColor(ShadowColor.NONE);
style.shadowColor(ShadowColor.shadowColor(NamedTextColor.RED, 0.4);
style.shadowColor(NamedTextColor.RED);
style.shadowColor(myBukkitColorObject);
style.shadowColor(ShadowColor.shadowColor(0xRRGGBBAA);
```

2024-12-06 03:40 UTC, zml2008 commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/standard/ShadowColorTagResolver.java
> +    final String colorString = args.popOr("Expected to find a color parameter: #RRGGBBAA").lowerValue();
Should we support something like `<shadow:red:0.5>` for this?

2024-12-06 05:27 UTC, zml2008 commented
this will need serializer support at some point too

2024-12-07 22:00 UTC, zml2008 commented
another thing we should add: a `<!shadow>` MM tag to disable shadows

2024-12-08 22:10 UTC, zml2008 commented
I think this has everything on my list now

2024-12-10 18:27 UTC, kezz requested changes, later dismissed
Minor changes, otherwise this looks fab

2024-12-10 18:27 UTC, kezz commented on api/src/main/java/net/kyori/adventure/text/Component.java
> +  default @NotNull Component shadowColor(final @Nullable ARGBLike argb) {
Is it worth mentioning here, or in the docs, that setting this to null doesn't _remove_ the shadow colour, it just restores it to default?

2024-12-10 18:27 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/standard/StandardTags.java
> +   * @since 4.10.0
```suggestion
   * @since 4.18.0
```

2024-12-14 06:19 UTC, zml2008 approved these changes

2024-12-15 17:31 UTC, merged