api: Add Audience.toAudience() collector
KyoriPowered/adventure pull request #156
Opened 2020-09-14 21:07 UTC by astei

This arose out of somewhat related discusion that led to #155 being filed, but it's not related.

This API adds a collector for `Audience`s. It is a convenient and idiomatic shorthand for `Audience.of(stream.collect(Collectors.toList()))` and is more concise: `stream.collect(Audience.toAudience())`

2020-09-14 22:00 UTC, kashike requested changes

2020-09-14 22:53 UTC, astei commented on api/src/main/java/net/kyori/adventure/audience/Audience.java
> +  static @NonNull Collector<? super Audience, Collection<Audience>, ForwardingAudience> toAudience() {
I'm -1 on this, it makes static imports too hard to read: `stream.collect(collector())` is probably quite confusing. `stream.collect(toAudience())` is unambiguous.

2020-09-15 02:53 UTC, kashike approved these changes

2020-10-10 18:51 UTC, kashike approved these changes

2020-10-10 18:51 UTC, merged