Make fallback locale configurable
KyoriPowered/adventure pull request #162
Opened 2020-09-28 13:40 UTC by lucko

2020-09-28 13:43 UTC, kashike requested changes

2020-09-28 13:43 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/TranslationRegistryImpl.java
> +    final String property = System.getProperty("net.kyori.adventure.defaultLocale");
```suggestion
    final String property = System.getProperty("net.kyo".concat("ri.adventure.defaultLocale");
```

2020-10-06 00:21 UTC, Electroid commented
I don't think this will work with a global translator -- if 1 plugin changes the default, it's likely to break another plugin that depends on another default.

2020-10-09 08:50 UTC, lucko commented
@Electroid Yep, I agree - I made another PR #167 to resolve this.

2020-10-11 06:04 UTC, kashike commented
#179

2020-10-11 06:04 UTC, closed without merging