Translation improvements
KyoriPowered/adventure pull request #179
Opened 2020-10-11 00:59 UTC by zml2008

One more step on top of @lucko's work, to restrict conflicting registrations.

2020-10-11 01:04 UTC, kashike requested changes

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/TranslationSource.java
> +  Key name();
```suggestion
  @NonNull Key name();
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/TranslationSource.java
> +  Collection<String> keys();
```suggestion
  @NonNull Collection<String> keys();
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/TranslationRegistryImpl.java
> +  public Key name() {
```suggestion
  public @NonNull Key name() {
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/TranslationRegistryImpl.java
> +  public Collection<String> keys() {
```suggestion
  public @NonNull Collection<String> keys() {
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/GlobalTranslationSourceImpl.java
> +  public Key name() {
```suggestion
  public @NonNull Key name() {
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/GlobalTranslationSourceImpl.java
> +  public Collection<String> keys() {
```suggestion
  public @NonNull Collection<String> keys() {
```

2020-10-11 01:04 UTC, kashike commented on api/src/main/java/net/kyori/adventure/translation/GlobalTranslationSourceImpl.java
> +        throw new IllegalArgumentException("Translation key '" + key + "' was found in both the " + source.name() + " and " + existing.name() + " translation sources!");
Perhaps something like ``Cannot register translation key {key} from {source} as it has already been registered from {existing]`?

2020-10-12 14:25 UTC, lucko approved these changes

2020-10-13 01:00 UTC, kashike approved these changes

2020-10-13 01:00 UTC, merged