Customize Debugger Output
KyoriPowered/adventure pull request #231
Opened 2020-12-10 07:29 UTC by zml2008

This adds some extra annotations to our main hierarchical data structures -- `Component`s and NBT that give a more streamlined view of objects in the debugger.

## Component

**Before:** 
![Before](https://cdn.discordapp.com/attachments/439651296434454529/786462343399604224/unknown.png)

**After:**
![After](https://cdn.discordapp.com/attachments/439651296434454529/786461378910093352/unknown.png)

(the implementation of this is a bit ugly at the moment -- perhaps there's space to improve it with changes to `examination`?)

## NBT

**Before:** 
![image](https://user-images.githubusercontent.com/629092/101734920-e6a3a100-3a75-11eb-8eeb-c2dca0eb0b61.png)

**After:**: 
![image](https://user-images.githubusercontent.com/629092/101735089-2e2a2d00-3a76-11eb-8b33-42731068097a.png)

2020-12-10 07:50 UTC, kashike requested changes

2020-12-10 07:50 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
> -      ExaminableProperty.of("children", this.children),
Looks like this got left out somehow.

2020-12-11 00:32 UTC, kashike commented on nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTagImpl.java
> +@Debug.Renderer(text = "\"ListBinaryTag(type=\" + this.type.toString() + \")\"", childrenArray = "this.tags.toArray()", hasChildren = "!this.tags.isEmpty()")
```suggestion
@Debug.Renderer(text = "\"ListBinaryTag[\" + this.type.toString() + \"}\"", childrenArray = "this.tags.toArray()", hasChildren = "!this.tags.isEmpty()")
```

2020-12-11 02:32 UTC, zml2008 commented on nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTagImpl.java
> +@Debug.Renderer(text = "\"ListBinaryTag(type=\" + this.type.toString() + \")\"", childrenArray = "this.tags.toArray()", hasChildren = "!this.tags.isEmpty()")
`[` or `{`? :p

2020-12-11 02:35 UTC, kashike commented on nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTagImpl.java
> +@Debug.Renderer(text = "\"ListBinaryTag(type=\" + this.type.toString() + \")\"", childrenArray = "this.tags.toArray()", hasChildren = "!this.tags.isEmpty()")
`[` I think?

2021-03-02 00:04 UTC, kashike approved these changes

2021-03-02 00:17 UTC, merged