api: Correct handling of children in some text replacements
KyoriPowered/adventure pull request #233
Opened 2020-12-11 22:35 UTC by zml2008

Fixes GH-232

I've taken this chance to re-organize the text replacement tests, since the API is no longer part of `TextComponent`.

2020-12-12 10:58 UTC, ForceUpdate1 commented
Thank you very much for the PR. I have tested it and found another issue.
I have created a test, which fails.

```
  @Test
  void testReplaceChild(){
    Component base = Component.text("value");

    Component replaced = base.replaceText(TextReplacementConfig.builder().match("value").replacement((BiFunction<MatchResult, TextComponent.Builder, ComponentLike>) (matchResult, builder) -> {
      return Component.text("").append(Component.text("1337"));
    }).build());

    Component expected = Component.text()
      .content("").append(Component.text("1337"))
      .build();
    assertEquals(expected, replaced);
  }
```

Testoutput:

```
Expected :TextComponentImpl{content="", children=[TextComponentImpl{content="1337", children=[], style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}}], style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}}
Actual   :TextComponentImpl{content="", children=[], style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}}
```

2020-12-12 11:21 UTC, zml2008 commented
Thanks for your testing! I've pushed a fix for that issue to this PR as well -- hopefully that takes care of your issues :)

2020-12-12 21:42 UTC, kashike requested changes

2020-12-12 21:42 UTC, kashike commented on api/src/test/java/net/kyori/adventure/text/TextReplacementRendererTest.java
> +public class TextReplacementRendererTest {
```suggestion
class TextReplacementRendererTest {
```

2020-12-13 08:03 UTC, kashike approved these changes

2020-12-13 08:03 UTC, merged