extension-kotlin
KyoriPowered/adventure pull request #283
Opened 2021-02-22 09:37 UTC by kashike

Replaces #139.

2021-02-22 09:39 UTC, BomBardyGamer reviewed
Very nice looking DSL! Would love to have this in the future!

2021-02-22 13:46 UTC, BomBardyGamer approved these changes

2021-02-24 02:56 UTC, CrushedPixel commented
Beautiful DSL, indeed!

2021-02-26 20:34 UTC, zml2008 requested changes

2021-02-26 20:34 UTC, zml2008 commented on extension-kotlin/build.gradle
> +  id "org.jetbrains.kotlin.jvm" version "1.4.30-M1"
```suggestion
  id "org.jetbrains.kotlin.jvm" version "1.4.30"
```

2021-02-26 23:21 UTC, zml2008 approved these changes

2021-03-01 06:18 UTC, zml2008 approved these changes

2021-03-01 17:23 UTC, kashike commented
@ItsDoot could you please review this?

2021-03-01 23:24 UTC, ItsDoot approved these changes

2021-03-01 23:24 UTC, ItsDoot commented on extra-kotlin/build.gradle
> +  id "org.jetbrains.kotlin.jvm" version "1.4.30-M1"
1.4.31

2021-03-02 00:05 UTC, merged