Added ZLIB compression support for NBT
KyoriPowered/adventure pull request #284
Opened 2021-02-24 10:07 UTC by BomBardyGamer

Added support for ZLIB using `InflatedInputStream` and `DeflatedOutputStream` to compress and decompress respectively. Has been tested.

2021-02-24 10:13 UTC, kashike requested changes

2021-02-24 10:13 UTC, kashike commented on nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
> +
```suggestion
```

2021-02-24 10:13 UTC, kashike commented on nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
> +      @NonNull InputStream decompress(@NonNull InputStream is) {
```suggestion
      @NonNull InputStream decompress(final @NonNull InputStream is) {
```

2021-02-24 10:13 UTC, kashike commented on nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
> +      @NonNull OutputStream compress(@NonNull OutputStream os) {
```suggestion
      @NonNull OutputStream compress(final @NonNull OutputStream os) {
```

2021-02-26 20:33 UTC, zml2008 approved these changes

2021-02-26 20:39 UTC, kashike approved these changes

2021-02-26 23:20 UTC, merged