api: Add support for 'compacting' components
KyoriPowered/adventure pull request #308
Opened 2021-03-13 23:20 UTC by zml2008

Closes GH-114

This ports the implementation of component compacting over from the original Kotlin provided by @CrushedPixel (see that [here](https://paste.gg/p/zml/89fb51d013064ad6b6bb279c7486d378#componentoptimizationtest-kt-l141))d 

While this component optimization is expensive enough that it shouldn't be used on every message sent, it can be useful for ensuring components of unknown origin (such as loaded from a configuration, or built from multiple sources) are as compact as possible before being sent to users.

Some things to discuss:

- The name: Does `compact` make sense, or should we use something else like `optimize` or `pack`?
- Should a setting be added to the serializers (mainly the Configurate serializer, but possibly others) to auto-compact when loading?

2021-05-12 21:38 UTC, octylFractal approved these changes
kewl, maybe call it `optimize` if you're gonna call it that internally anyways

2021-08-01 00:06 UTC, kashike requested changes

2021-08-01 00:06 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/ComponentCompacting.java
> +    if(parentStyle != null) {
```suggestion
    if (parentStyle != null) {
```
(entire pull request needs reformatting)

2021-08-01 00:07 UTC, kashike requested changes

2021-08-01 00:07 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/Component.java
> +   * @since 4.8.0
```suggestion
   * @since 4.9.0
```

2021-08-02 21:49 UTC, kashike approved these changes

2021-08-02 21:51 UTC, merged