WIP: Add weather API
KyoriPowered/adventure pull request #321
Opened 2021-03-31 16:08 UTC by kezz

# Weather
This PR adds a weather module to Adventure, providing an API for controlling the weather. The current implementation is more of a proof of concept then a final design. I'm not even 100% sure if such a thing fits in Adventure like this, or if it could be its own repo or something completely different. I'm most interested in hearing what everyone thinks!

## Holder
Similar to `Audience` the weather module includes the concept of a `WeatherHolder`, that being something that can have weather applied and checked. The current weather can be obtained from a holder using `WeatherHolder#weather()` and can be set using `WeatherHolder#weather(Weather)`.

Additionally, the concept of a `ChildWeatherHolder` exists. This represents an object that either has its own weather, or has the weather of it's parent. For example, a player could have their own weather overriding that of the world's weather.

## Weather
The `Weather` object itself is constructed using a type and a length. The type is one of rain, clear or thunder, mimicking the `/weather` command in vanilla Minecraft. The length object either holds an exact duration or is marked as random, mimicking the natural flow of weather in whatever platform you are using.

## Examples
Here's some examples of how the system would work.

```java
// clear the weather for five minutes in a world
world.weather(Weather.clear());

// nope let's make it rain for a random length of time
world.weather(Weather.rain(Length.random()));

// assuming player is a child of world, this would be true
var isTrue = player.weather().type() == Type.RAIN;

// however, we can override the weather for the child - this could have a Length.forever() method
player.weather(Weather.clear(Length.of(ChronoUnit.FOREVER.getDuration())));

// now the child has it's own weather, this will be false
var isFalse = player.weather.type() == Type.RAIN;
```

2021-03-31 16:15 UTC, kashike requested changes
codestyle

2021-03-31 16:15 UTC, kashike commented on weather/src/main/java/net/kyori/adventure/weather/Weather.java
> +  static @NonNull Weather rain(Weather.@NonNull Length length) {
```suggestion
  static @NonNull Weather rain(final @NonNull Length length) {
```

2021-03-31 16:15 UTC, kashike commented on weather/src/main/java/net/kyori/adventure/weather/Weather.java
> +  static @NonNull Weather thunder(Weather.@NonNull Length length) {
```suggestion
  static @NonNull Weather thunder(final @NonNull Length length) {
```

2021-03-31 16:15 UTC, kashike commented on weather/src/main/java/net/kyori/adventure/weather/Weather.java
> +  static @NonNull Weather weather(final @NonNull Type type, Weather.@NonNull Length length) {
```suggestion
  static @NonNull Weather weather(final @NonNull Type type, final @NonNull Length length) {
```

2021-03-31 16:15 UTC, kashike commented on weather/src/main/java/net/kyori/adventure/weather/Weather.java
> +  @NonNull Type type();
Move this above the `length()` getter.

2021-03-31 16:15 UTC, kashike commented on weather/src/main/java/net/kyori/adventure/weather/Weather.java
> +    THUNDER
```suggestion
    THUNDER;
```

2021-03-31 18:05 UTC, Electroid commented
I would agree with @TheMolkaPL here.

2021-04-09 12:03 UTC, kezz commented
I wonder if this is something that might be better suited in another repo, perhaps `adventure-extra` or something with a different name entirely to handle weather alongside other aspects of Minecraft that could be abstracted into an API like this? Each part would be its own module so that they could be implemented part by part if desired.

2021-04-29 01:33 UTC, Electroid commented
Appreciate the rationale. Deciding what's in and out of scope is one of the most challenging parts of maintaining a project. I think though we have some consensus that weather, even in an "extra" project, is out of scope.

2021-04-29 01:33 UTC, closed without merging