Add reconfiguration methods to LegacyComponentSerializer.Builder
KyoriPowered/adventure pull request #374
Opened 2021-05-20 20:41 UTC by A248

Adds methods to LegacyComponentSerializer builder to undo options already set on it.

2021-05-23 07:42 UTC, kashike requested changes

2021-05-23 07:42 UTC, kashike commented on text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
>      @NonNull Builder useUnusualXRepeatedCharacterHexFormat();
```suggestion
    default @NonNull Builder useUnusualXRepeatedCharacterHexFormat() {
      return this.useUnusualXRepeatedCharacterHexFormat(true);
    }
```

2021-05-23 07:42 UTC, kashike commented on text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
> +    @NonNull Builder useUnusualXRepeatedCharacterHexFormat(boolean flag);
```suggestion
    @NonNull Builder useUnusualXRepeatedCharacterHexFormat(final boolean flag);
```

2021-05-23 07:42 UTC, kashike commented on text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
> +    @NonNull Builder hexColors(boolean flag);
```suggestion
    @NonNull Builder hexColors(final boolean flag);
```

2021-06-04 11:58 UTC, lucko approved these changes

2021-09-07 20:32 UTC, kezz approved these changes
`@since` tags need updating before merging.

2022-03-30 16:10 UTC, kezz commented
@A248 do you plan to update this PR with the requested changes to since tags and annotations?

2022-03-31 01:59 UTC, A248 commented
I have no plans to do such things myself. Anyone else is free to continue this PR where I left off.

2022-04-01 10:30 UTC, closed without merging