api: Add inVersion to all @ApiStatus.ScheduledForRemoval annotations
KyoriPowered/adventure pull request #451
Opened 2021-09-21 17:52 UTC by NoahvdAa

Fixes #450.

2021-09-21 17:53 UTC, kezz approved these changes

2021-09-21 19:47 UTC, kashike approved these changes

2021-09-22 06:17 UTC, Proximyst approved these changes

2021-09-22 07:52 UTC, kezz commented
Actually, whilst you're looking at deprecations - there's quite a few deprecations that aren't annotated with `@ApiStatus.ScheduledForRemoval`. Could you perhaps touch those too?

2021-09-22 20:38 UTC, kezz requested changes

2021-09-22 20:38 UTC, kezz commented on api/src/main/java/net/kyori/adventure/util/ShadyPines.java
> +
No spaces between imports

2021-09-23 09:33 UTC, kezz approved these changes
Thanks for the PR :)

2021-09-25 17:20 UTC, zml2008 approved these changes

2021-09-25 17:21 UTC, merged