Add Tristate method to TextDecoration.State
KyoriPowered/adventure pull request #495
Opened 2021-11-03 18:31 UTC by KingOfSquares

Felt like a naturally missing piece

2021-11-03 18:34 UTC, kezz requested changes

2021-11-03 18:34 UTC, kezz commented on api/src/main/java/net/kyori/adventure/text/format/TextDecoration.java
> +      return byBoolean(flag.toBoolean());
Should have a require not null check on the flag

2021-11-03 19:11 UTC, kashike requested changes

2021-11-03 19:11 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/format/TextDecoration.java
> +      return byBoolean(flag.toBoolean());
Think I'd prefer a `switch` here.

2021-11-03 20:58 UTC, kezz approved these changes

2021-11-03 22:36 UTC, BomBardyGamer commented
Wouldn't it also be useful to add a `asTriState` conversion method, so you can convert a state to its tri state representation?

2021-11-03 22:39 UTC, kezz commented
> Wouldn't it also be useful to add a `asTriState` conversion method, so you can convert a state to its tri state representation?

I don't think so. This comes back to the reason they aren't the same in the first place. A `TriState` will never have its values change but a `TextDecoration.State` might.

2021-11-03 23:28 UTC, kashike approved these changes

2021-11-10 17:29 UTC, zml2008 approved these changes

2021-11-10 17:30 UTC, merged