Abstract out style methods to StyleWriter/Reader
KyoriPowered/adventure pull request #501
Opened 2021-11-21 21:58 UTC by KingOfSquares

Closes #491

Also solves some other minor inconsistencies like:
- Adds font methods to `Component`
- Adds the `#decorate(Set<TextDecoration> decorations, boolean flag)` everywhere (Not just `ComponentBuilder`)
- Adds `@ApiStatus.NonExtendable` to `ComponentBuilder` (in addition to the new interfaces)

Should these get their own PR? Excluding the second one

2021-11-21 23:44 UTC, kashike requested changes

2021-11-21 23:44 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/format/StyleWriter.java
> + * @see net.kyori.adventure.text.format.Style
```suggestion
 * @see Style
```

2021-11-21 23:44 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/format/StyleWriter.java
> + * @param <T> The type implementing this interface, e.g. {@link net.kyori.adventure.text.Component}
```suggestion
 * @param <T> the type implementing this interface, e.g. {@link Component}
```

2021-11-21 23:44 UTC, kashike commented on api/src/main/java/net/kyori/adventure/text/format/StyleReader.java
> +  @ApiStatus.Internal TextDecoration[] DECORATIONS = TextDecoration.values();
Access this from a package-private class instead.

2021-12-11 04:37 UTC, zml2008 requested changes
The general concept/impl looks good here. However, in `adventure-nbt` we use a `Setter` suffix -- see `ListTagSetter` and `CompoundTagSetter`. Do we want to change these names to `StyleGetter` and `StyleSetter` to match?

2021-12-12 21:32 UTC, zml2008 approved these changes

2021-12-13 01:18 UTC, kashike approved these changes

2021-12-13 01:21 UTC, merged