text-minimessage: Reduce the API surface of the parse context a little bit
KyoriPowered/adventure pull request #623
Opened 2021-12-07 05:44 UTC by zml2008

Can more of these methods be removed? The only truly essential one is imo `parse(String)`, but I'm not sure what sort of usecases others might have

2021-12-07 05:59 UTC, kashike commented
It's definitely easier to add methods as-required, versus deprecating and removing methods later on.

2021-12-11 08:41 UTC, kezz requested changes

2021-12-11 08:41 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/Context.java
> +public interface Context {
Should we annotate this with a non-extendible notice?

2021-12-11 19:07 UTC, kezz requested changes

2021-12-11 19:07 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/Context.java
> +  String originalMessage();
```suggestion
  @NotNull String originalMessage();
```

2021-12-11 19:07 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/Context.java
> +  Component parse(String message);
```suggestion
  @NotNull Component parse(final @NotNull String message);
```

2021-12-11 19:31 UTC, kezz approved these changes

2021-12-11 19:32 UTC, merged