Implement MiniMessage preprocessor and cleanup parsing
KyoriPowered/adventure pull request #749
Opened 2022-04-08 19:55 UTC by bluelhf

This pull request combines two changes to MiniMessage, one internal and the other external.

On the user-facing side, a new feature is implemented: **preprocessing**. This is essentially exactly opposite to the existing post-processing in MiniMessage: it's simply a unary operator that is applied to every string input prior to deserialising it into a tree.

On the internal side, this also removes the explicit `richMessage` parameters from most MiniMessageParser methods, opting to instead deduce the value from ContextImpl where possible. A notable outlier here is the process of escaping tokens, where the `richMessage` parameter is explicitly required for escaping to work.

2022-04-09 09:49 UTC, kezz requested changes
Just the tiniest of nitpicks :p

2022-04-09 09:49 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessage.java
> +     * @param preProcessor method run at the end of parsing
```suggestion
     * @param preProcessor method run at the start of parsing
```

2022-04-09 12:14 UTC, bluelhf commented
> Just the tiniest of nitpicks :p

whoopsies, i guess that's what i get for copy & paste :D

2022-04-09 13:14 UTC, kezz approved these changes
Thanks for the PR! :)

2022-04-09 23:31 UTC, kashike requested changes

2022-04-09 23:31 UTC, kashike commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/ContextImpl.java
> +    final UnaryOperator<Component> postProcessor) {
```suggestion
    final UnaryOperator<Component> postProcessor
  ) {
```

2022-05-26 12:48 UTC, bluelhf commented
oh whoops sorry kezz didnt mean to press buttons

2022-05-30 03:55 UTC, zml2008 commented
Out of curiosity, what was your planned usecase for this pre-processing function?

2022-05-31 07:09 UTC, bluelhf commented
> Out of curiosity, what was your planned usecase for this pre-processing function?

I believe the initial use-case for this was a preprocessor that word wraps the input prior to building the components — the discussion that led to this change is in the [#adventure channel on the Kyori discord server](https://discord.com/channels/319355592605040642/923037274176913409/962039867695579156)

2022-06-01 03:07 UTC, zml2008 approved these changes

2022-06-01 03:07 UTC, merged