text-minimessage: Add a TagResolver for boolean values
KyoriPowered/adventure pull request #857
Opened 2023-01-10 20:52 UTC by JOO200

This will add a new TagResolver for boolean values.

Instead of passing number values or timestamps you want to display some text when a condition is met.

E.g. the text `The issuer is a player` for players and `The issuer is a console` for consoles. Currently that's not easily possible.

With the new tag you can use:
```java
MiniMessage.miniMessage().deserialize("The issuer is a <isplayer:player:console>.", 
    Formatter.booleanChoice("isPlayer", isPlayer)
);
```

2023-01-10 21:18 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +   * @since 4.12.0
```suggestion
   * @since 4.13.0
```

2023-02-12 21:43 UTC, zml2008 requested changes

2023-02-12 21:43 UTC, zml2008 commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +      final String falseCase = argumentQueue.popOr("Talse format expected.").value();
```suggestion
      final String falseCase = argumentQueue.popOr("False format expected.").value();
```

:p

2023-02-13 00:19 UTC, zml2008 approved these changes

2023-02-13 04:23 UTC, kashike approved these changes

2023-02-13 04:40 UTC, merged