feat(key): try to include additional information in error messages when an invalid character has been detected in a Key
KyoriPowered/adventure pull request #887
Opened 2023-03-26 17:42 UTC by kashike

2023-03-26 17:43 UTC, jpenilla requested changes

2023-03-26 17:43 UTC, jpenilla commented on key/src/main/java/net/kyori/adventure/key/KeyImpl.java
> +        "Non [a-z0-9_.-] character in %s of Key[%s] at index %d (%s, bytes: %s)",
```suggestion
        "Non [a-z0-9_.-] character in %s of Key[%s] at index %d ('%s', bytes: %s)",
```

2023-03-26 18:14 UTC, jpenilla approved these changes

2023-03-26 18:45 UTC, kezz requested changes

2023-03-26 18:45 UTC, kezz commented on key/src/main/java/net/kyori/adventure/key/Key.java
> +   * @return {@link OptionalInt#empty()} if {@code value} is a valid namespace, {@code false} otherwise
docs here are wrong

2023-03-26 18:45 UTC, kezz commented on key/src/main/java/net/kyori/adventure/key/Key.java
> +   * @return {@link OptionalInt#empty()} if {@code value} is a valid value, {@code false} otherwise
also here

2023-04-28 15:02 UTC, kezz approved these changes

2023-04-30 18:46 UTC, zml2008 approved these changes

2023-04-30 18:55 UTC, merged