chore: rename static in HoverEvent.ShowItem
KyoriPowered/adventure pull request #923
Opened 2023-05-11 19:41 UTC by powercasgamer

Crosses of an item in #454

2023-05-11 23:33 UTC, kashike approved these changes

2023-05-12 03:53 UTC, zml2008 approved these changes

2023-05-12 04:01 UTC, zml2008 requested changes
```
> Task :adventure-text-serializer-gson:compileTestJava
/home/runner/work/adventure/adventure/text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/TranslatableComponentTest.java:69: warning: [deprecation] of(Key,UUID,Component) in ShowEntity has been deprecated
          .hoverEvent(HoverEvent.showEntity(HoverEvent.ShowEntity.of(
                          
```

one last deprecation from Actions

2023-05-12 11:07 UTC, powercasgamer commented
> ```
> > Task :adventure-text-serializer-gson:compileTestJava
> /home/runner/work/adventure/adventure/text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/TranslatableComponentTest.java:69: warning: [deprecation] of(Key,UUID,Component) in ShowEntity has been deprecated
>           .hoverEvent(HoverEvent.showEntity(HoverEvent.ShowEntity.of(
>                           
> ```
> 
> one last deprecation from Actions

fixed

2023-05-12 14:46 UTC, zml2008 approved these changes

2023-05-12 15:05 UTC, merged