feat(mini-message): add Formatter#join
KyoriPowered/adventure pull request #938
Opened 2023-06-25 22:19 UTC by tahmid-23

This PR adds a method to Formatter to join components using JoinConfiguration.

2023-06-25 22:24 UTC, zml2008 requested changes, later dismissed
This is a nice addition -- just a few comments. Could you also open a PR on `adventure-docs` documenting this addition?

2023-06-25 22:24 UTC, zml2008 commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +   * @since 4.14.0
```suggestion
   * @since 4.15.0
```

4.14.0 has already been released.....

2023-06-25 22:24 UTC, zml2008 commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +   * @since 4.14.0
same here

2023-06-25 22:24 UTC, zml2008 commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +  public static TagResolver join(@TagPattern final @NotNull String key, final @NotNull Iterable<? extends ComponentLike> components) {
maybe call this `joining`?

2023-06-25 23:15 UTC, tahmid-23 commented
from what I can see, there is also a lastSeparatorIfSerial method which is mutually exclusive, in terms of functionality, with lastSeparator
should I add something like <tag:separator:last_separator:serial>? or <tag:separator:last_separator:true>? in order to use lastSeparatorIfSerial

2023-06-26 09:01 UTC, kezz commented
> from what I can see, there is also a lastSeparatorIfSerial method which is mutually exclusive, in terms of functionality, with lastSeparator should I add something like tag:separator:last_separator:serial? or tag:separator:last_separator:true? in order to use lastSeparatorIfSerial

IIRC `lastSeparatorIfSerial` is only used where there are three or more elements in the list (e.g. `x, y, and z`). It will still use `lastSeparator` in the case where there are two elements (e.g. `x and y`).

2023-06-26 11:56 UTC, Joo200 commented
I already use such a resolver for my project but I don't use a collection of ComponentLike. Instead I use a Collection of TagResolvers instead, with:
```java
  public static TagResolver joining(@TagPattern final @NotNull String key, final @NotNull Iterable<? extends TagResolver> components) {
    return TagResolver.resolver(key, (arguments, ctx) -> {
        String format = arguments.popOr("expected list format").value();
        String separator = arguments.popOr("expected separator").value();
        if (arguments.hasNext()) {
            String emptyVal = arguments.pop().value();
            if (resolvers.isEmpty()) return Tag.inserting(ctx.deserialize(emptyVal));
        }
        List<Component> components = resolvers.stream().map(r -> ctx.deserialize(format, r)).toList();
        Component separatorComponent = ctx.deserialize(separator);
        Component all = components.stream().collect(Component.toComponent(separatorComponent));

        if (arguments.hasNext()) {
            int amount = arguments.popOr("maximum amount").asInt().orElse(5);
            String lastInfo = arguments.popOr("last entry").value();
            String hoverFormat = arguments.popOr("hover").value();
            if (resolvers.size() > amount) {
                Component hover = ctx.deserialize(hoverFormat,
                        Formatter.number("total", resolvers.size()),
                        Formatter.number("remaining", resolvers.size() - amount),
                        Placeholder.component("all", all));
                Component remaining = ctx.deserialize(lastInfo,
                        Formatter.number("total", resolvers.size()),
                        Formatter.number("remaining", resolvers.size() - amount)).hoverEvent(hover);
                return Tag.selfClosingInserting(components.stream().limit(amount).collect(Component.toComponent(separatorComponent)).append(remaining));
            }
        }
        return Tag.selfClosingInserting(all);
  });
}
```

My implementation is complex and I don't think we should use that as api. However you can easily change the format of the list entries, e.g. with such a minimessage format string
```
Governors: <gray><governors:'<online:green:gray><name></online>':', ':'<dark_gray>-- no one --</dark_gray>':'5':'<gold> and <remaining> more</gold>':'<gold>Total <total> governors:<br><gray><all>'>
```
This will be formatted to:
```
Governors: First, second, third, forth, fifth and 3 more.
```
Where `and 3 more` has an hover effect.

I don't think we should add such complex logic to minimessage however I would add the TagResolver approach as you can easily modify the formatting.

2023-07-16 18:42 UTC, tahmid-23 commented
I added an argument for lastSeparatorIfSerial.

I'm not sure if TagResolvers are the best approach here.
Personally, I think I think that using Components would be more convenient. If I needed a placeholder, I could render it myself.

2024-07-28 18:03 UTC, tahmid-23 commented
any love? :slightly_smiling_face:

2024-10-30 17:21 UTC, kezz requested changes
Minor changes that can be done before merge

2024-10-30 17:21 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +   * <p>This tag expects a separator as the first argument. A last separator may optionally be provided.</p>
Can this be optional too? In the case where you're happy to just use `JoinConfiguration.noSeparators`?

2024-10-30 17:21 UTC, kezz commented on text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/tag/resolver/Formatter.java
> +   * @since 4.15.0
Need updating before merge

2024-10-30 17:33 UTC, kezz approved these changes
Made the changes myself, LGTM :p

2024-12-08 22:27 UTC, zml2008 approved these changes

2024-12-10 08:01 UTC, merged

2024-12-10 16:17 UTC, tahmid-23 commented
now if only I still played Minecraft... 😛