feature: Add a new standard join configuration for spaces
KyoriPowered/adventure pull request #962
Opened 2023-08-13 20:13 UTC by RedDaedalus

Adds `JoinConfiguration.spaces()`, which is equivalent to `JoinConfiguration.separator(Component.space())`. Unit tests and docs are both provided.

2023-08-13 20:14 UTC, zml2008 requested changes

2023-08-13 20:14 UTC, zml2008 commented on api/src/main/java/net/kyori/adventure/text/JoinConfiguration.java
> +   * @since 4.14.0
```suggestion
   * @since 4.15.0
```

4.14.0 has already been released

2023-08-18 08:32 UTC, kezz approved these changes

2023-08-26 23:45 UTC, zml2008 approved these changes

2023-08-27 00:01 UTC, merged